version: "3.7"

services:
  db:
    image: postgres:14.0-alpine
    container_name: database
    volumes:
      - ./fixtures/movies_dmp.sql:/docker-entrypoint-initdb.d/movies_dmp.sql
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - etl/.env
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: .
    container_name: etl
    volumes:
      - etl_state:/state/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - etl/.env
    networks:
      - etl

volumes:
  postgres_data:
  etl_state:

networks:
  db:
    name: s4_network
  etl:
    name: s4_network
