version: "3.7"

services:
  db:
    image: postgres:14.0-alpine
    container_name: database
    volumes:
      - ./fixtures/movies_dmp.sql:/docker-entrypoint-initdb.d/movies_dmp.sql
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - etl/.env
    networks:
      - db
  etl:
    build: .
    container_name: etl
    volumes:
      - etl_state:/opt/state/
    depends_on:
      - db
    env_file:
      - etl/.env
    networks:
      - etl

volumes:
  postgres_data:
  etl_state:

networks:
  db:
    name: s4_network
  etl:
    name: s4_network
